### PR TITLE
Write new lesson on static methods and default methods in interfaces

### PR DESCRIPTION
**Pull request by kcleland0818**

### CODE REVIEW

**Review by linda-seiter — COMMENTED** [review]
-Suggestion, reword as "that have the same signature"
The diamond problem is when a class inherits two methods that are the same.


- Can we also show example of calling one of the default methods as a solution to the diamond problem:
Vehicle.super.turnAlarmOff();

- Maybe add reminder that static methods can't be overriden.

**Comment by kcleland0818** [comment]
Let me know if my explanation of the keyword super made any sense at all.

**Review by linda-seiter — APPROVED** [review]
Should this be parent interface's?

This provides us
access to the superclass or parent class' methods.

**Comment by kcleland0818** [comment]
> Should this be parent interface's?
> 
> This provides us access to the superclass or parent class' methods.

Yes it should! Good catch

**Review by developerjaym — APPROVED** [review]

**Review by linda-seiter — APPROVED** [review]

**Pull request merged**
